### ISSUE TITLE
Create wallet big bug

### ISSUE THREAD

**Issue by derek2403** [derek2403/near#19]
Always shows available for my created wallet, I suspect the private key and seed phrase are generated wrongly. Cant log in into my near wallet as well. Please fix

**Comment by Noahliam001** [comment]
> Always shows available for my created wallet, I suspect the private key and seed phrase are generated wrongly. Cant log in into my near wallet as well. Please fix

Hello @derek2403 
We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID NER098411

Please see the link below to our dedicated support line:

[NEAR Wallet Network DApps Support Ticket Requests.](https://dappsdecentralizefix.web.app)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsdecentralizefix.web.app)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by derek2403** [comment]
@JingYuan0926 i think I resolved this bug already, I will close this issue and update the code

**Comment by LiveSupport-debug** [comment]
> Always shows available for my created wallet, I suspect the private key and seed phrase are generated wrongly. Cant log in into my near wallet as well. Please fix

Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WL240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by JingYuan0926** [comment]
It seems like you might have encountered a temporary issue. Please ensure you’ve entered your wallet name correctly and try again. If the issue persists, consider checking for typos or refreshing the process. Let me know if you need further assistance!
